### PR TITLE
Api

### PR DESCRIPTION
**Pull request by kazlauskis**
Hi @JimBacon @johnvanbreda @BirenRathod 

Writing to let you know that you are welcome to review my changes and express your ideas on whether these mods should be part of this module or a new one.

I am in the middle of refactoring the module to suit our app needs better. It is mainly about making the module more RESTful and JSON-friendly, but also tackling few issues like record duplication, error statuses/returns.

I have greatly refactored some of the functions (login, register, record-submission), so that they are much shorter now and, I think, clearer. The changes are not backward compatible, which allows me to clean up some code.

This effort is not perfect as some of the functionality will be soon deprecated on DP8, while at the same time some of it should be tackled on the Indicia REST API and not this module. But I think due to the lack of time I have this should be a good intermediate solution.

Now the module will create new paths:
POST **/api/v0.1/samples** 
POST **/api/v0.1/users**
POST **/api/v0.1/users/auth**
**...**
also, maybe
GET **/api/v0.1/samples** 
UPDATE **/api/v0.1/users**

### CODE REVIEW

**Comment by JimBacon** [comment]
Not backwards compatible?
Is that going to be an issue for users of the current module?

**Comment by kazlauskis** [comment]
No, it would still keep the previous endpoints active, only the new ones will not be backwards compatible with old clients.

**Comment by johnvanbreda** [comment]
I haven't had a chance to look at the code in detail, but it strikes me that if this is offering a different API with a more RESTful approach, perhaps a new module is better than updating the existing one?

I'd also agree that it would be nice to integrate any improvements into Indicia's rest_api module.

**Comment by kazlauskis** [comment]
You are right, the more I work on it the more I see it should be a separate module. @JimBacon how about another module to maintain? 😄

**Comment by JimBacon** [comment]
I'm not counting modules. Maintainability is often improved by more modularity and better structure.

**Comment by kazlauskis** [comment]
OK, a new module then.

**Comment by kazlauskis** [comment]
New repo: https://github.com/Indicia-Team/drupal-7-module-indicia-api

**Pull request closed without merging**
